custom_parameters:
  - target_name: &target_name Genesis-Plus-GX

language: cpp

before_script:
  - mkdir build
  - cd build

matrix:
  include:
  - os: windows
    script:
      - cmake -G "Visual Studio 15 2017" -A Win32
      - cmake --build . --target *target_name --config Release
