custom_parameters:
  - cmake_build_target_command: &cmake_build_target_command cmake --build . --target Genesis-Plus-GX --config Release

language: cpp

before_script:
  - mkdir build
  - cd build

matrix:
  include:
  - os: windows
    script:
      - cmake -G "Visual Studio 15 2017" -A Win32 ..
      - *cmake_build_target_command
